image: node:12-alpine

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - node_modules

stages:
  - prepare
  - test

npm-install:
  stage: prepare
  script:
    - npm ci

test-unit:
  stage: test
  script:
    - npm run test

test-e2e:
  stage: test
  script:
    - npm run e2e
